### ISSUE TITLE
What should I do when the Failed to load RTCore driver problem occurs?

### ISSUE THREAD

**Issue by who-am-i-c** [CVNLD/CFGComp#1]

**Comment by CVNLD** [comment]
Run with --debug and post the full output here please

**Comment by who-am-i-c** [comment]
[DEBUG] Program started
[DEBUG] Running with administrator privileges
[DEBUG] COE file: {}C:\Users\Administrator\Desktop\Pcie\save\I225V2\pcileech_cfgspace.coe
[DEBUG] Raw PCI Address input: {}7:00.0
Parsing COE file: C:\Users\Administrator\Desktop\Pcie\save\I225V2\pcileech_cfgspace.coe
COE file parsing complete. Lines read: 275
COE data size: 4096 bytes
Extracted Vendor ID: 0x8086, Device ID: 0x15f3
[DEBUG] COE data size: {} bytes4096
[DEBUG] Parsed PCI Address: {:X}:{:X}:{:X}700
[DEBUG] Attempting to extract driver to: {}C:\Users\Administrator\AppData\Local\Temp\RTCore64.sys
[DEBUG] Driver file extracted successfully to: {}C:\Users\Administrator\AppData\Local\Temp\RTCore64.sys
[DEBUG] Driver extracted successfully. Attempting to load...
[DEBUG] StartService failed. Error: {}183
[DEBUG] [ERROR] Failed to load RTCore driver.

C:\Users\Administrator\Desktop\cfgcomp>

**Comment by CVNLD** [comment]
This is happening because the same driver is loaded elsewhere, likely either MSI Afterburner or drvscan

**Comment by who-am-i-c** [comment]
Thanks, I'll try that, I think I have drvscan enabled.
